# Swagger/OpenAPI
quarkus.smallrye-openapi.path=/docs/openapi
quarkus.swagger-ui.path=/docs/swagger-ui
quarkus.swagger-ui.title=Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Mastodon (Streaming)
quarkus.smallrye-openapi.info-license-name=MIT License
quarkus.smallrye-openapi.info-license-url=https://en.wikipedia.org/wiki/MIT_License

# Sentry
quarkus.log.sentry.dsn=https://e47b8742451c4187bb48cb86eb336183@sentry.wigger.one/7
quarkus.log.sentry.in-app-packages=*
quarkus.log.sentry.level=ERROR

# Logging
quarkus.log.level=${LOG_LEVEL:INFO}

# Metrics
quarkus.micrometer.export.prometheus.path=/metrics